# Generated by Django 3.2.15 on 2022-08-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=2048)),
                ('fecha_empezado', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
                ('autor', models.ManyToManyField(to='notasPensamiento.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notasPensamiento.bibliografia')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Extracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracto', models.CharField(max_length=5000)),
                ('posicion', models.IntegerField()),
                ('pensar', models.CharField(max_length=10)),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notasPensamiento.bibliografia')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notasPensamiento.capitulo')),
                ('etiqueta', models.ManyToManyField(to='notasPensamiento.Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TiposExtracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Zettelcasten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=5000)),
                ('etiqueta', models.ManyToManyField(to='notasPensamiento.Etiqueta')),
                ('extracto', models.ManyToManyField(to='notasPensamiento.Extracto')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=2048)),
                ('comentario', models.CharField(max_length=1000)),
                ('consultado', models.CharField(max_length=10)),
                ('bibliografia', models.ManyToManyField(to='notasPensamiento.Bibliografia')),
                ('tipo', models.ManyToManyField(to='notasPensamiento.Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='extracto',
            name='tipo',
            field=models.ManyToManyField(to='notasPensamiento.TiposExtracto'),
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='tipo',
            field=models.ManyToManyField(to='notasPensamiento.Tipo'),
        ),
    ]
