# Generated by Django 3.2.15 on 2022-09-10 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='etiqueta_hijo',
            field=models.ManyToManyField(related_name='_notasPensamiento_etiqueta_etiqueta_hijo_+', to='notasPensamiento.Etiqueta'),
        ),
        migrations.AddField(
            model_name='zettelcasten',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zettelcasten',
            name='zettlecasten',
            field=models.ManyToManyField(related_name='_notasPensamiento_zettelcasten_zettlecasten_+', to='notasPensamiento.Zettelcasten'),
        ),
    ]
