# Generated by Django 3.2.15 on 2022-09-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0002_auto_20220910_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliografia',
            name='url',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='etiqueta_hijo',
            field=models.ManyToManyField(blank=True, related_name='_notasPensamiento_etiqueta_etiqueta_hijo_+', to='notasPensamiento.Etiqueta'),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='capitulo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='notasPensamiento.capitulo'),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='posicion',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='comentario',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='consultado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='zettelcasten',
            name='extracto',
            field=models.ManyToManyField(blank=True, to='notasPensamiento.Extracto'),
        ),
        migrations.AlterField(
            model_name='zettelcasten',
            name='zettlecasten',
            field=models.ManyToManyField(blank=True, related_name='_notasPensamiento_zettelcasten_zettlecasten_+', to='notasPensamiento.Zettelcasten'),
        ),
    ]
