# Generated by Django 3.2.15 on 2022-09-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0003_auto_20220911_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracto',
            name='bibliografia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='notasPensamiento.bibliografia'),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='pensar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='tipo',
            field=models.ManyToManyField(blank=True, to='notasPensamiento.TiposExtracto'),
        ),
        migrations.AlterField(
            model_name='zettelcasten',
            name='date_creation',
            field=models.DateField(blank=True),
        ),
    ]
