# Generated by Django 3.2.15 on 2022-09-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0004_auto_20220911_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracto',
            name='bibliografia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notasPensamiento.bibliografia'),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='capitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notasPensamiento.capitulo'),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='etiqueta',
            field=models.ManyToManyField(null=True, to='notasPensamiento.Etiqueta'),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='extracto',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='pensar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extracto',
            name='tipo',
            field=models.ManyToManyField(blank=True, null=True, to='notasPensamiento.TiposExtracto'),
        ),
    ]
