# Generated by Django 3.2.15 on 2022-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0005_auto_20220911_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='en_bibliografia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
