# Generated by Django 3.2.15 on 2022-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0007_alter_extracto_pensar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliografia',
            name='existe',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bibliografia',
            name='autor',
            field=models.ManyToManyField(blank=True, null=True, to='notasPensamiento.Autor'),
        ),
        migrations.AlterField(
            model_name='bibliografia',
            name='fecha_empezado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bibliografia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bibliografia',
            name='tipo',
            field=models.ManyToManyField(blank=True, null=True, to='notasPensamiento.Tipo'),
        ),
        migrations.AlterField(
            model_name='bibliografia',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
