# Generated by Django 3.2.15 on 2022-09-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0009_tipo_existe'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracto',
            name='huerfano',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='referencia',
            name='huerfano',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zettelcasten',
            name='huerfano',
            field=models.IntegerField(default=1),
        ),
    ]
