# Generated by Django 3.2.15 on 2022-09-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0010_auto_20220911_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zettelcasten',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, to='notasPensamiento.Etiqueta'),
        ),
    ]
