# Generated by Django 3.2.15 on 2022-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasPensamiento', '0011_alter_zettelcasten_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='etiqueta_padre',
            field=models.ManyToManyField(blank=True, related_name='_notasPensamiento_etiqueta_etiqueta_padre_+', to='notasPensamiento.Etiqueta'),
        ),
        migrations.AlterField(
            model_name='zettelcasten',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zettelcasten',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, null=True, to='notasPensamiento.Etiqueta'),
        ),
        migrations.AlterField(
            model_name='zettelcasten',
            name='extracto',
            field=models.ManyToManyField(blank=True, null=True, to='notasPensamiento.Extracto'),
        ),
        migrations.AlterField(
            model_name='zettelcasten',
            name='huerfano',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='zettelcasten',
            name='zettlecasten',
            field=models.ManyToManyField(blank=True, null=True, related_name='_notasPensamiento_zettelcasten_zettlecasten_+', to='notasPensamiento.Zettelcasten'),
        ),
    ]
