# Generated by Django 4.1.3 on 2022-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notasPensamiento", "0013_auto_20220926_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracto",
            name="comentario",
            field=models.CharField(default="", max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="etiqueta",
            name="etiqueta_hijo",
            field=models.ManyToManyField(blank=True, to="notasPensamiento.etiqueta"),
        ),
        migrations.AlterField(
            model_name="etiqueta",
            name="etiqueta_padre",
            field=models.ManyToManyField(blank=True, to="notasPensamiento.etiqueta"),
        ),
        migrations.AlterField(
            model_name="zettelcasten",
            name="zettlecasten",
            field=models.ManyToManyField(
                blank=True, null=True, to="notasPensamiento.zettelcasten"
            ),
        ),
    ]
